<template>
  <div>
    <h3>Este é uma funcionalidade do NextJs e ReactJs</h3>

    <div class="modal" :class="{ 'is-active': show }">
      <div class="modal-background"></div>
      <div class="modal-card" style="width: 400px">
        <div class="card">
          <div class="card-content" style="background-color: white">
            <button
              class="delete"
              aria-label="close"
              @click="closeADS"
            ></button>
            <img
              class="img-modal"
              src="https://www.meioemensagem.com.br/wp-content/uploads/2021/07/Como-ganhar-dinheiro-com-marketing-de-afiliado.jpg"
            />
            <p class="subtitle-modal-form">
              Inscreva-se agora e comece a aproveitar todos os benefícios de ser
              um afiliado do AfilI-Pay!
            </p>
            <input
              class="input form-modal-input"
              type="text"
              placeholder="Coloque o Email que você mais usa"
            />
            <button class="button is-link is-light">QUERO DESCONTO</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'teste',
  layout: blank,
  head() {
    return {
      title: 'Testando funcionalidades NextJs',
      meta: [{ name: 'description', content: 'Generated by create next app' }],
      link: [{ rel: 'icon', href: '/pro.ico' }],
    };
  },

  data() {
    return {
      show: true,
    };
  },

  methods: {
    closeADS() {
      this.show = false;
    },
  },
};
</script>

<style>
.form-modal-input {
  border: 0.5px solid silver;
  margin-bottom: 10px;
}
.subtitle-modal-form {
  color: black;
  size: 16px !important;
  margin-top: 20px;
}
button[class='button is-link is-light'] {
  width: 100%;
}

.img-modal {
  width: 100%;
}
</style>
