<script>
export default {
  head() {
    return {
      title: 'Testando funcionalidades NextJs',
      meta: [{ name: 'description', content: 'Generated by create next app' }],
      link: [{ rel: 'icon', href: '/pro.ico' }],
    };
  },
  render() {
    return (
      <div>
        <h3>Este é uma funcionalidade do NextJs e ReactJs</h3>
      </div>
    );
  },
};
</script>
